"""add campo status ao agendamento

Revision ID: 24e6c5f73028
Revises: 
Create Date: 2025-07-01 11:05:42.833715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e6c5f73028'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_envio', sa.DateTime(), nullable=False),
    sa.Column('destinatario', sa.String(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('tipo_comunicacao', sa.Enum('email', 'sms', 'push', 'whatsapp', name='tipocomunicacaoenum'), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'enviado', 'erro', 'cancelado', name='statusagendamentoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    # ### end Alembic commands ###
